# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "zombie_passenger_killer"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = "2012-01-05"
  s.email = "michael@grosser.it"
  s.executables = ["zombie_passenger_killer"]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "bin/zombie_passenger_killer",
    "lib/zombie_passenger_killer.rb",
    "spec/spec_helper.rb",
    "spec/zombie_passenger_killer_spec.rb",
    "zombie_passenger_killer.gemspec"
  ]
  s.homepage = "http://github.com/grosser/zombie_passenger_killer"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Guaranteed zombie passengers death"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

