# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require 'zombie_passenger_killer/version'

Gem::Specification.new do |s|
  s.name = %q{zombie_passenger_killer}
  s.version = ZombiePassengerKiller::Version

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = %q{2011-09-09}
  s.default_executable = %q{zombie_passenger_killer}
  s.email = %q{michael@grosser.it}
  s.executables = ["zombie_passenger_killer"]
  s.files       = `git ls-files`.split("\n")
  s.files      -= ['.rvmrc', '.gitignore']
  s.homepage = %q{http://github.com/grosser/zombie_passenger_killer}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Guaranteed zombie passengers death}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

